blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/StartsMercury/cr-publish/discussions
    about: |
      Please use Issues exclusively for reporting bugs, suggesting enhancements to existing functionality, and requesting new features.

      For general questions, assistance requests, and broader community discussions, please visit our GitHub Discussions space.

  - name: Documentation
    url: https://github.com/StartsMercury/cr-publish#cr-publish
    about: |
      Explore our comprehensive documentation to gain valuable insights into using cr-publish effectively within your workflows.

      If you encounter any issues or have suggestions for improving the documentation, feel free to open an issue or participate in our Discussions.
